################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
NAME        = "zperfmq"
VERSION     = "0.0.0"
LICENSE     = "lgpl 3"
DESCRIPTION = """Python bindings of: zeromq performance measurement tool"""
URL         = "https://github.com/brettviren/zperfmq"
PACKAGES    = ["zperfmq"]
REQUIRES    = [
    "czmq",
]
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
