/*  =========================================================================
    zperfmq - generated layer of public API

    LGPL 3.0

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZPERFMQ_LIBRARY_H_INCLUDED
#define ZPERFMQ_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  ZPERFMQ version macros for compile-time API detection
#define ZPERFMQ_VERSION_MAJOR 0
#define ZPERFMQ_VERSION_MINOR 0
#define ZPERFMQ_VERSION_PATCH 0

#define ZPERFMQ_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZPERFMQ_VERSION \
    ZPERFMQ_MAKE_VERSION(ZPERFMQ_VERSION_MAJOR, ZPERFMQ_VERSION_MINOR, ZPERFMQ_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ZPERFMQ_STATIC
#       define ZPERFMQ_EXPORT
#   elif defined ZPERFMQ_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define ZPERFMQ_EXPORT __declspec(dllexport)
#       else
#           define ZPERFMQ_EXPORT
#       endif
#   elif defined ZPERFMQ_EXPORTS
#       define ZPERFMQ_EXPORT __declspec(dllexport)
#   else
#       define ZPERFMQ_EXPORT __declspec(dllimport)
#   endif
#   define ZPERFMQ_PRIVATE
#elif defined (__CYGWIN__)
#   define ZPERFMQ_EXPORT
#   define ZPERFMQ_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define ZPERFMQ_PRIVATE __attribute__ ((visibility ("hidden")))
#       define ZPERFMQ_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define ZPERFMQ_PRIVATE
#       define ZPERFMQ_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  ZPERFMQ_BUILD_DRAFT_API
#define ZPERFMQ_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef ZPERFMQ_BUILD_DRAFT_API
typedef struct _zperf_t zperf_t;
#define ZPERF_T_DEFINED
typedef struct _zperf_msg_t zperf_msg_t;
#define ZPERF_MSG_T_DEFINED
typedef struct _zperf_server_t zperf_server_t;
#define ZPERF_SERVER_T_DEFINED
typedef struct _zperf_client_t zperf_client_t;
#define ZPERF_CLIENT_T_DEFINED
typedef struct _perf_t perf_t;
#define PERF_T_DEFINED
#endif // ZPERFMQ_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef ZPERFMQ_BUILD_DRAFT_API
#include "zperf.hpp"
#include "zperf_msg.hpp"
#include "zperf_server.hpp"
#include "zperf_client.hpp"
#include "perf.hpp"
#endif // ZPERFMQ_BUILD_DRAFT_API

#ifdef ZPERFMQ_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
ZPERFMQ_EXPORT void
    zperfmq_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // ZPERFMQ_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
