/*  =========================================================================
    zperf_node - API to a zperf agent which combines client, server and Zyre actor.

    LGPL 3.0
    =========================================================================
*/

#ifndef ZPERF_NODE_H_INCLUDED
#define ZPERF_NODE_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/zperf_node.xml" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef ZPERFMQ_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Create a zperf node.
ZPERFMQ_EXPORT zperf_node_t *
    zperf_node_new (void);

//  *** Draft method, for development use, may change without warning ***
//  Destroy the zperf_node.
ZPERFMQ_EXPORT void
    zperf_node_destroy (zperf_node_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Create a server, return status code.
ZPERFMQ_EXPORT uint8_t
    zperf_node_server (zperf_node_t *self, const char *server_name);

//  *** Draft method, for development use, may change without warning ***
//  Create a client, return status code.
ZPERFMQ_EXPORT uint8_t
    zperf_node_client (zperf_node_t *self, const char *client_name);

//  *** Draft method, for development use, may change without warning ***
//  Announce self to the zyre network.
//
//  Call this after all servers have been initialized.
//
//  Return our zyre peer id.
ZPERFMQ_EXPORT const char *
    zperf_node_publish (zperf_node_t *self, const char *nickname);

//  *** Draft method, for development use, may change without warning ***
//  Return a hash of zyre peer IDs and nick names.
ZPERFMQ_EXPORT zhash_t *
    zperf_node_peers (zperf_node_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Return information about a zyre peer.
ZPERFMQ_EXPORT zhash_t *
    zperf_node_peer_info (zperf_node_t *self, const char *peerid);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
ZPERFMQ_EXPORT void
    zperf_node_test (bool verbose);

#endif // ZPERFMQ_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
